config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :todo_lists do
    resources :todo_items do
    	member do
    		patch :complete
    	end
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :posts

  
  root 'pages#index'
  get 'explore', to: 'pages#explore'
  get 'home', to: 'pages#home'
  get '/user/:id', to: 'pages#profile'

  
  resources :articles
  
  

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create]

	def create
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		redirect_to @todo_list
	end

	def destroy
		if @todo_item.destroy
			flash[:success] = "Todo List item was deleted."
		else
			flash[:error] = "Todo List item could not be deleted."
		end
		redirect_to @todo_list
	end

	def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_item
		@todo_item = @todo_list.todo_items.find(params[:id])
	end

	def todo_item_params
		params[:todo_item].permit(:content)
	end

end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :content, rows: 1, class: "form-group", placeholder: "New to do item" %>
	<br>
	<%= f.submit class: "btn btn-primary btn-todo" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row1 clearfix">
	<% if todo_item.completed? %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<br>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		
		<br><br>
		<div class ="todobtns">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= todo_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>