config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :todo_lists do
    resources :todo_items do
    	member do
    		patch :complete
    	end
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :posts

  
  root 'pages#index'
  get 'explore', to: 'pages#explore'
  get 'home', to: 'pages#home'
  get '/user/:id', to: 'pages#profile'

  
  resources :articles
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 250}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action  :set_article, only:[:edit, :update, :show, :destroy]
    def index
   @list = Article.all
    end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    if @article.update (article_params)
      flash[:success] = "Article succesfully updated"
      redirect_to article_path(@article)
      else
      render 'edit'
    end
  end

  def create
    @article = Article.new(article_params)
   if  @article.save
     flash[:success] = "Article was successfully created"
    redirect_to article_path(@article)
     else
    render 'new'
   end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  private
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class = 'row'>
  <div class = 'col-xs-12'>
    <%= form_for(@article, :html =>{class:'form-horizontal', role: 'form'}) do |f| %>
    <div class = 'form-group'>
      <div class = 'control-label col-sm-2'>
      <%= f.label :title %>
      </div>
      <div class = 'col-sm-6'>
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
      </div>
    </div>
    <div class = 'form-group'>
      <div class = 'control-label col-sm-2'>
        <%= f.label :description %>
      </div>
      <div class = 'col-sm-6'>
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article description" %>
      </div>
    </div>

    <div class = "form-group">
      <div class = "col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>

    <% end %>

      <div class = "col-xs-4 col-xs-offset-4">
        [ <%= link_to "Cancel request and return to article list", articles_path %> ]

           </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align= "center"> Edit existing articles </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align = "center"> Listing all articles! </h1>

<% @list.each do |article| %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
    <div class = "well well-lg">
      <div class = "article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class = "article-body">
    <%= truncate(article.description, length: 40) %>
      </div>
   `<div class = "article-actions">

    <%= link_to "Edit article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete article", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>

      </div>
    </div>
  </div>
</div>
  <% end %>

app/views/articles/new.html.erb
<h1 align = "center"> Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align = "center"> Title: <%= @article.title %> </h2>
<div class = "well col-xs-8 col-xs-offset-2">
  <h4 class = "center description"><strong> Description: </strong> </h4>
<hr>
  <%= simple_format(@article.description)%>
`<div class = "article-actions">

  <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
  <%= link_to "Delete article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
 <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success"  %>
  </div>
</div>