config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :todo_lists do
    resources :todo_items do
    	member do
    		patch :complete
    	end
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :posts

  
  root 'pages#index'
  get 'explore', to: 'pages#explore'
  get 'home', to: 'pages#home'
  get '/user/:id', to: 'pages#profile'

  
  resources :articles
  
  

end

app/views/layouts/_footer.html.erb
<% if !user_signed_in? %>
  
  <% else %>
 
  <%= render 'layouts/footer_user' %>
  
  <% end %>

app/views/layouts/_footer_user.html.erb
<div class = "container">
  <div class = footer>
    <small>
      Copyright &copy; JungoPeanuts </small>
    <nav>
      <ul>
        <li><%= link_to "Made for FiiCode" %> </li>
      </ul> </nav>
  </div>
  </div

app/views/layouts/_messages.html.erb
<div class = "row">
  <div class = "col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>
    <div class = 'alert alert-<%= "#{name}" %> '>
      <a href = "#" class = "close" data-dismiss = "alert"> &#215; </a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
 
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<% if !user_signed_in? %>
  <%= render 'layouts/navigation_guest' %>
  <% else %>
  <%= render 'layouts/navigation_user' %>
  <% end %>

app/views/layouts/_navigation_guest.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      
    </div>
   
 <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", articles_path %> </li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
    
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Navigation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Sign up', new_user_registration_path) %>
            <li role="seperator" class = "divider"></li>
            <li><%= link_to('Sign in', new_user_session_path) %></li>
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_user.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

     
      <!-- <%= link_to "EZ TASK", root_path, class: "navbar-brand", id: "logo" %> -->
    </div>

     <img class = "navbar-brand" src = "/list.png">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Explore", explore_path %></li>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Articles", articles_path %> </li>
        <li><%= link_to "Checklist", todo_lists_path %></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
         <li>
           <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search Easy Task ">
          </div>
        </form>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.username %>">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create new article", new_article_path %>
            <li role="separator" class="divider"></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Edit profile', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
            
          </ul>
           <li type = "button" class = "btn btn-primary navbar-btn">Instant Posts</li>
        </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_slide.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
    <% link_to image_tag("/05-large.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image"} %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<% if params[:id] != nil %>
  <% @url = '/user/' + params[:id] %>
  <% if current_page?(@url) %>
    <img src="/03-large.jpg" class="profile-banner">
    <div class="row">
      <div class="col-sm-12" style="background-color: white;">
        <div class="container">
          <div class="col-sm-3">&nbsp;</div>
          <div class="col-sm-6" style="margin-top: 5px">
            <div class="col-sm-2" style="font-size: 100%; opacity: 0.7;">POSTS<br>
                    <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).posts.count %></h6></div>
            <div class="col-sm-2" style="font-size: 100%; opacity: 0.7;">FOLLOWERS<br>
                   <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).followers.count %></h6>
            <% if user_signed_in? %>
              <div class="col-sm-8" style="text-align: right; margin-top: 5px; float: right;"><a href="/users/edit">
                <li type="button" class="btn btn-default" style="color: grey; opacity: 0.8; font-weight: bold;">EDIT PROFILE</li></a></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
  <div class = "container">

  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>